name: 'Publish NuGet Package'
description: 'Packs a .NET project and publishes it to the Vicgital GitHub Packages NuGet feed'

inputs:
  startupProject:
    description: 'Path to the .csproj file to pack'
    required: true
  githubPublishPackageToken:
    description: 'Github authentication token used to push the package, tipically the {{ secrets.GITHUB_TOKEN }}'
    required: true
  githubPackageUsername:
    description: 'The Github auth username used to retore dependency packages'
    required: true
  githubPackageToken:
    description: 'The Github auth PAT used to retore dependency packages'
    required: true
  dotnetVersion:
    description: '.NET SDK version to use'
    required: false
    default: '10.0.x'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}

    - name: Pack
      env:
        GH_PACKAGE_USERNAME: ${{ inputs.githubPackageUsername }}
        GH_PACKAGE_TOKEN: ${{ inputs.githubPackageToken }}
      shell: bash
      run: dotnet pack "${{ inputs.startupProject }}"  -c Release -o ./nupkg

    - name: Push to GitHub Packages
      shell: bash
      run: dotnet nuget push "./nupkg/*.nupkg" --source "https://nuget.pkg.github.com/vicgital/index.json" --api-key ${{ inputs.githubPublishPackageToken }} --skip-duplicate
